### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by scottmwyant** [Milys/NC-Gcode-VSCode#5]
My observations: 
- VS Code extension marketplace is reporting nearly 11k installs
- Last commit October 11, 2018 (88bb238978baa6e8f4bdb0100eee22bd3cf3ab72)
- There are 3 open issues and 1 open PR.  Oldest issue is from November 11, 2018.  There does not appear to be any activity or communication on any of these topics.

My request is for the owner to respond with a suggestion on how to maintain this repo.  Judging by the number of downloads, the community has a need for this type of extension.  There are alternatives  already in the marketplace but this one has the most downloads.

**Comment by Milys** [comment]
Hey Scott, Thank You for your email and interest in Nc-Gcode extension,
I am really busy and don't have time to support this extension.
I added you to this extension as collaborator. 
If you have any questions let me know.
Mitch.

**Comment by scottmwyant** [comment]
Getting a little ahead of myself but how does the extension get updated in
the marketplace?  I see your extension is published by ‘mietek’.

I am familiar with the publishing workflow as an individual but not as part
of a team.

Of course, no urgency to this, just let me know how you want to proceed.

-Scott

**Comment by scottmwyant** [comment]
@Milys Looks like you have to also grant me permissions to your (ML or "mietek") publisher on http://marketplace.visualstudio.com.

**Comment by scottmwyant** [comment]
@Milys An alternative would be to go into the settings for this repo and put the token into the encrypted secrets section.  I would not be able to see the token but I would be able to use it programmatically to publish an update to the marketplace (since now we have GitHub Actions).

**Comment by scottmwyant** [comment]
@Milys,
 
I've been working on my fork of the repository.  At some point I'd to get updates to the marketplace.  If I don't hear from you in the next month or so I will be obligated to use my own publisher which means, I will be publishing my own extension and users of the NC-Gcode extension will not be aware of the update.

Best,
SMW

**Comment by stevos758** [comment]
Any news on this? Still waiting on the .pit files to be included.

**Comment by scottmwyant** [comment]
@Milys, - If you'd like me to be able to update your extension rather than publish another version, grant 'creator' permission to scottmwyant@gmail.com in [your publisher settings](https://marketplace.visualstudio.com/manage/publishers/ML).  

Reference the image below.
![Capture](https://user-images.githubusercontent.com/29161635/84557405-e4e06700-acf8-11ea-9668-cb08429350c0.PNG)

**Comment by scottmwyant** [comment]
New extension released as [ML2.nc-gcode](https://marketplace.visualstudio.com/items?itemName=ML2.nc-gcode). Please see readme.md
